/**
 * KingsOrder
 */
/**
 * All the app constants comes here
 */


 //*> CONFIGURATIONS
 export const API_TIMEOUT = 30000;

 //*> API CALLING CONSTANTS
export const GET_API = 'GET';
export const POST_API = 'POST';
export const PUT_API = 'PUT';
export const DELETE_API = 'DELETE';
export const UPDATE_API = 'PUT';

//*> APP LOADER
export const START_SPINNER = "START_SPINNER"  
export const STOP_SPINNER = "STOP_SPINNER"

//*> ERROR MODAL
export const SHOW_ERROR_MODAL = "SHOW_ERROR_MODAL"  
export const HIDE_ERROR_MODAL = "HIDE_ERROR_MODAL"

//*> USER CONSTANTS
export const ONBOARDING = 'ONBOARDING';
export const LOGIN_USER = 'LOGIN_USER';
export const SIGNUP_USER = 'SIGNUP_USER';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const FORGOT_PASSWORD_OTP = 'FORGOT_PASSWORD_OTP';
export const GET_USER_PROFILE_DATA = 'GET_USER_PROFILE_DATA';
export const UPLOAD_USER_PROFILE_IMAGE = 'UPLOAD_USER_PROFILE_IMAGE';
export const GET_ABOUT_US = 'GET_ABOUT_US';
export const GET_CONTACT_US = 'GET_CONTACT_US';
export const GET_POLICY = 'GET_POLICY';
export const POST_FEEDBACK = 'POST_FEEDBACK';

//*> FOOD CONSTANTS
export const GET_ALL_FOOD_LIST = 'GET_ALL_FOOD_LIST';
export const GET_ALL_FOOD_CATEGORY_LIST = 'GET_ALL_FOOD_CATEGORY_LIST';
export const GET_ALL_FOOD_MENU_LIST = 'GET_ALL_FOOD_MENU_LIST';
export const GET_FOOD_BY_CATEGORY_LIST = 'GET_FOOD_BY_CATEGORY_LIST';
export const GET_TRENDING_FOOD_LIST = 'GET_TRENDING_FOOD_LIST';

//*> SHOP CONSTANTS
export const GET_TRENDING_SHOP_LIST = 'GET_TRENDING_SHOP_LIST';
export const GET_ALL_SHOP_LIST = 'GET_ALL_SHOP_LIST';
export const GET_ALL_SHOP_CATEGORY_LIST = 'GET_ALL_SHOP_CATEGORY_LIST';
export const GET_ALL_SHOP_MENU_LIST = 'GET_ALL_SHOP_MENU_LIST';
export const GET_SHOP_BY_CATEGORY_LIST = 'GET_SHOP_BY_CATEGORY_LIST';

//*> GADGET CONSTANTS
export const GET_ALL_GADGET_LIST = 'GET_ALL_GADGET_LIST';
export const GET_ALL_GADGET_CATEGORY_LIST = 'GET_ALL_GADGET_CATEGORY_LIST';
export const GET_ALL_GADGET_MENU_LIST = 'GET_ALL_GADGET_MENU_LIST';
export const GET_GADGET_BY_CATEGORY_LIST = 'GET_GADGET_BY_CATEGORY_LIST';

//*> MART CONSTANTS
export const GET_ALL_MART_CATEGORY_LIST = 'GET_ALL_MART_CATEGORY_LIST';
export const GET_MART_CATEGORY_BY_NAME_LIST = 'GET_MART_CATEGORY_BY_NAME_LIST';

//*> VENDOR CONSTANTS
export const VENDOR_REDISTARTION = 'VENDOR_REDISTARTION';
export const EMPLOYEE_REGISTARTION = 'EMPLOYEE_REGISTARTION';

//*> CART CONSTANTS
export const GET_CART_BY_EMAIL = 'GET_CART_BY_EMAIL';
export const GET_FOOD_SEARCH_LIST = 'GET_FOOD_SEARCH_LIST';
export const ADD_CART_ITEM = 'ADD_CART_ITEM';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';
export const REMOVE_CART_ITEM_BY_ID = 'REMOVE_CART_ITEM_BY_ID';

//*> REBATE AND PROMO CONSTANTS
export const GET_ALL_PROMO_TAB_LIST = 'GET_ALL_PROMO_TAB_LIST';
export const GET_ALL_REBATE_TAB_LIST = 'GET_ALL_REBATE_TAB_LIST';

//*> SERVICE CATEGORY CONSTANTS
export const GET_ALL_SERVICE_CATEGORY_LIST = 'GET_ALL_SERVICE_CATEGORY_LIST';
export const GET_ALL_SERVICE_SUB_CATEGORY_LIST = 'GET_ALL_SERVICE_SUB_CATEGORY_LIST';
export const GET_BOOKING_ORDER_BY_DATE = 'GET_BOOKING_ORDER_BY_DATE';
export const GET_ALL_SERVICE_SUB_CATEGORY_LIST_BY_NAME = 'GET_ALL_SERVICE_SUB_CATEGORY_LIST_BY_NAME';
export const SAVE_SERVICE_ORDER = 'SAVE_SERVICE_ORDER';